### ISSUE TITLE
Lazy may signal an error, causing emacs to stop loading the init.el

### ISSUE THREAD

**Issue by ercdude** [lambdart/lazy-load#1]
If a directory of `lazy-files-alist` does not exists, when lazy try to add a watch `file-notify-add-watch` signals an error, which is not handled.

Adding a condition (like a `when` as the example bellow) avoid the problem, but it's not a good solution. Maybe there is a way to catch the signal before it's thrown to `init.el`?

```
(defun lazy--add-file-notify-watch (dirs)
  "Add DIRS to the notifications system: `filenotofy'.
Push the returned file descriptor `lazy-file-descriptors' list."
  ;; iterate over the directories list
  (dolist (dir dirs)
    ;; add only if directory exists
    (when (file-exists-p dir)
      ;; add descriptor to the `lazy-file-descriptors' list
      (push
       ;; add a file-notify watcher
       (file-notify-add-watch dir
                              '(change attribute-change)
                              'lazy--file-notify-callback)
       ;; descriptors internal list
       lazy-file-descriptors))))
```

**Comment by lambdart** [comment]
Seems like a 'late time decision' problem, how about ensure the directory files exists (or create them) before the `lazy--add-file-notify-watch' call?

**Comment by ercdude** [comment]
I don't think that ignoring the directory is a bad idea, it would ensure a defined behavior. The directory may be removed after the setup, as an example.

Also, the default directories does not ensure that either. Maybe it should check when defining?

```
(defcustom lazy-files-alist
  (list
   ;; lisp directory
   (cons "lisp-loaddefs.el"
         (expand-file-name "lisp/" user-emacs-directory))
   ;; site-lisp directory
   (cons "site-lisp-loaddefs.el"
         (expand-file-name "site-lisp/" user-emacs-directory)))
```

**Comment by lambdart** [comment]
See: https://github.com/esac-io/lazy/commit/b882ea47a3805bd137051fda911c86a74b1e6ae3
